policy_terms:
  - grade
  - grading
  - policy
  - policies
  - regulation
  - regulations
  - requirement
  - requirements
  - academic standards
  - degree requirements
  - gre
  - gmat
  - english proficiency
  - toefl
  - ielts
  - duolingo
  - transfer credit
  - add/drop
  - withdrawal
  - leave of absence
  - pass/fail
  - probation
  - dismissal

tier_boosts:
  1: 1.25
  2: 1.10
  3: 1.00
  4: 1.00

intent:
  course_keywords: ["course descriptions", "show courses", "list courses", "prerequisite", "prerequisites", "syllabus"]
  degree_keywords:
    - ms
    - m.s.
    - phd
    - ph.d
    - mba
    - mfa
    - ma
    - msc
    - program requirements
    - curriculum
    - concentration
    - how many credits
    - credit requirement
    - admissions
    - gre
    - gpa
  course_code_regex: "\\b[A-Z]{3,5}\\s?\\d{3}[A-Z]?\\b"

nudges:
  policy_acadreg_url: 1.07
  same_program_bonus: 2.00            # used when alias_url matches same program family
  course_url_bonus: 1.80              # boost when URL is the course search/description page
  course_title_bonus: 1.40            # boost when title starts with the course code
  other_program_tier34_penalty: 0.25  # strong demotion for program pages on course queries

guarantees:
  ensure_tier1_on_policy: true
  ensure_tier4_on_program: true       # still true, but main.py disables this for course queries

tier4_gate:
  use_embedding: true
  min_title_sim: 0.35
  min_alt_sim: 0.32

retrieval_sizes:
  topn_default: 40
  topn_with_alias: 120
  k: 5

followups:
  hints:
    - "for "
    - "now "
    - "do it for"
    - "for the"
    - "make that for"
    - "do that for"
    - "do it"
    - "that"
    - "this"
    - "same"

# course retrieval strictness
course_filters:
  strict_subject_on_code: true   # only keep same-subject chunks for course-code queries
  tier3_bonus: 1.30              # keep from before